### ISSUE TITLE
Every time the Update happens the game freezes for around a second.

### ISSUE THREAD

**Issue by MaxderLange2008** [HEROgold/bot-batteries-technologies_1.0.0#1]
Hello there,
I have a World with the Mod Space Exploration.
Every time the Update Function of your mod is triggered the game freezes for about a second.
Is this a bug or is  it just because I have around 500 roboports in my world?
Greetings.

**Comment by HEROgold** [comment]
Hey thanks for the issue, which version are you using? it could happen that the game freezes a little bit when you have lots of roboports or when you have a very big discovered map, i'll look into fixing this.

**Comment by HEROgold** [comment]
I've implemented a fix for the lag spikes, tested it in a map with over 4K roboports, the upgrading of the roboports now happens gradually over time, removing lag spikes. For very big bases, with over thousands of roboports, it may take a few minutes before all roboports are updated. 

(updates Should be 1 roboport per tick, 60 per second and 3600 per minute, asuming 60 UPS)

**Comment by MaxderLange2008** [comment]
That fixed the issue. Thanks for the fast response.
