### ISSUE TITLE
Missing logistical roboport entity

### ISSUE THREAD

**Issue by Joemybird** [HEROgold/bot-batteries-technologies_1.0.0#6]
Unknown as to what the exact cause nor the extent that it goes to, but an issue occurred on my single player world regarding a 
mk-c4l4r2m2 logistical roboport.

There are already two other logistical roboports placed with Mk.0202, however, trying to place a new one causes the issue on placedown, whether manually or via bots.

The exact error message given is as follows:
`
The mod Roboport Technology (3.0.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event bot-batteries-technologies::on_robot_built_entity (ID 14)
Unknown entity name: logistical-roboport-mk-c4l4r2m2
stack traceback:
	[C]: in function 'create_entity'
	__bot-batteries-technologies__/control.lua:171: in function 'update_storage_roboport_level'
	__bot-batteries-technologies__/control.lua:255: in function 'update_roboport_level'
	__bot-batteries-technologies__/control.lua:354: in function 'on_built'
	__bot-batteries-technologies__/control.lua:374: in function <__bot-batteries-technologies__/control.lua:368>
`

The mod settings have not been changed and I have attempted removing and re-installing the mod incase if it would somehow resolve that.

**Comment by HEROgold** [comment]
Thanks for letting me known, I made a mistake when porting the mod to factorio 2.0.

I've answered the same question on [The mod portal](https://mods.factorio.com/mod/bot-batteries-technologies/discussion/6720945365681d9dfd8efdc3). 

> Try going to the settings of the mod, and setting the Research Minimum to a higher level..

In your case, this should at least be 4.

**Comment by Joemybird** [comment]
Thank you for your response! This has resolved my issue
